version: '3.8'

services:
  my-postgres-db:
    image: postgres
    container_name: todo-docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: unless-stopped

volumes:
  postgres_data:
